services:
  - type: web
    name: sama-api
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: cd backend && npm install && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 