services:
  - type: web
    name: sama-api
    env: node
    rootDir: backend
    buildCommand: cd .. && npm install && cd frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 